language: node_js

node_js:
  - '12'

cache:
  yarn: true
  directories:
    - 'node_modules'

jobs:
  include:
    - stage: bundlecheck
      script:
        - cd packages/cli
        - npm ci
        - npx ts-node src/bin/bundlecheck.ts --checkName bundlecheck-travis
