version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Bundlecheck
          command: |
            cd packages/cli
            npm ci
            npx ts-node src/bin/bundlecheck.ts --configName bundlecheck-circleci
