version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - run: cd packages/cli
      - run: npm ci
      - run: npx ts-node src/bin/bundlecheck.ts
