version: 2.1
jobs:
  bundlecheck:
    working_directory: packages/cli
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
        name: Install dependencies
        command: npm ci
      - save_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
        paths:
          - ./node_modules
      - run:
        name: Run bundlecheck
        command: npx ts-node src/bin/bundlecheck.ts --checkName bundlecheck-circleci
