version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    steps:
      - checkout
      - run: cd packages/cli
      - restore_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npx ts-node src/bin/bundlecheck.ts
