version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo

    steps:
      - checkout
      - run: ls
      - run: cd ./packages/cli
      - run: sudo npm install -g npm@latest
      - run: npm install
      - run: npx ts-node src/bin/bundlecheck.ts
