name: bundlecheck
on: [push]

jobs:
  bundlecheck:
    name: Bundlecheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - name: Boostrap monorepo
        run: |
          npm install
          npm run bootstrap
      - name: Run unit tests
        run: |
          npm run test:coverage
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@master
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Run bundlecheck
        env:
          BUNDLECHECK_GITHUB_TOKEN: ${{ secrets.BUNDLECHECK_GITHUB_TOKEN }}
        working-directory: packages/cli
        run: |
          npx ts-node src/bin/bundlecheck.ts
